version: '3.1'

services:

  ringsteki-client:
    image: node:11.11.0
    command: bash -c "npm install; HOST=0.0.0.0 SERVER_HOST=ringsteki-server npm run start"
    working_dir: /app
    ports:
      - 8080:8080
    volumes:
      - ./ringsteki-client:/app:cached
    depends_on: 
      - ringsteki-server
  
  ringsteki-server:
    image: node:11.11.0
    env_file:
     - ringsteki-server/.env
    command: bash -c "npm install; mkdir -p server/logs; node ."
    working_dir: /app
    ports:
      - 4000:4000
      - 9229:9229
      - 9230:9230
      - 9500:9500
      - 6000:6000
    volumes:
      - ./ringsteki-server:/app:cached
    depends_on: 
      - mongo
  
  mongo:
    image: mongo
    volumes:
      - db-data:/data/db

  mongo-express:
    image: mongo-express
    ports:
      - 8081:8081
    depends_on: 
      - mongo

volumes:
  db-data: