version: 2.1
orbs:
  heroku: circleci/heroku@0.0.8
jobs:
  build:
    docker:
      - image: circleci/node:lts

    steps:
      - setup_remote_docker
      - checkout
      - run:
          name: Pull submodules
          command: git submodule update --init --recursive
      - run:
          name: Installing client dependencies
          command: npm install
          working_directory: ringsteki-client
      - run:
          name: Building client vendor code
          command: npm run build-vendor
          working_directory: ringsteki-client
      - run:
          name: Build Client
          command: npm run build
          working_directory: ringsteki-client
      - run:
          name: Copy client build output to server
          command: |
            mkdir -p ringsteki-server/public
            cp ringsteki-client/dist/* ringsteki-server/public
            cp -R ringsteki-client/assets/* ringsteki-server/public
            cp ringsteki-client/assets.json ringsteki-server/.
            cp ringsteki-client/vendor-assets.json ringsteki-server/.
      - heroku/install
      - run:
          name: Login into Heroku Docker Repository
          command: |
            docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com
      - run:
          name: Build docker image and push to Heroku Repository
          command: heroku container:push web -a ringsteki
      - run:
          name: Release it!
          command: heroku container:release web -a ringsteki
  provision_db:
    docker:
      - image: circleci/node:lts
    steps:
      - checkout
      - run:
          name: Pull submodules
          command: git submodule update --init --recursive
      - run:
          name: Install dependencies
          command: npm install
          working_directory: ringsteki-server
      - run:
          name: Update DB
          command: npm run fetchdata
          working_directory: ringsteki-server
workflows:
  build_and_provision:
    jobs:
      - provision_db