version: 2
jobs:
  build:
    docker:
      - image: circleci/node:lts

    steps:
      - checkout
      - run:
          name: Pull submodules
          command: git submodule update --init --recursive
      - run:
          name: Build Client
          command: |
            echo "Installing dependencies"
            npm install
            npm run build
            npm run build-vendor 
          working_directory: ringsteki-client

      - run:
          name: Build Server
          command: |
            echo "Building server"